inherit_mode:
  merge:
    - Exclude

AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
    - app/**/*.rb
    - spec/**/*.rb
  Exclude:
    - bin/**/*
    - db/schema.rb
    - vendor/bundle/**/*
    - Gemfile

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "Rakefile"
    - "**/*.rake"
    - "spec/**/*.rb"

Metrics/LineLength:
  Enabled: false
