inherit_mode:
  merge:
    - Exclude

AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
    - app/**/*.rb
    - spec/**/*.rb
  Exclude:
    - bin/**/*
    - db/schema.rb
    - vendor/bundle/**/*

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false
