version: "3"

services:
  postgres:
    image: postgres:12.0
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - postgresql:/var/lib/postgresql
    restart: always

  api:
    image: sasalatart/hr-attendance-api
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - postgres
    restart: always

volumes:
  postgresql:
