ruby-cache-key: &ruby-cache-key v1-app-deps-{{ checksum "Gemfile.lock" }}
ruby-docker-image: &ruby-docker-image circleci/ruby:2.6.3
postgres-docker-image: &postgres-docker-image circleci/postgres:12.0
working-directory: &working-directory ~/repo

version: 2.1

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: *ruby-docker-image
        environment:
          BUNDLER_VERSION: 2.0.1
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: postgres

      - image: *postgres-docker-image

    working_directory: *working-directory

    steps:
      - checkout

      - restore_cache:
          keys:
            - *ruby-cache-key
            # fallback to using the latest cache if no exact match is found
            - v1-app-deps-

      - run:
          name: Setup Bundler
          command: gem install bundler:2.0.1

      - run:
          name: Install Dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          key: *ruby-cache-key
          paths:
            - ./vendor/bundle

      - run:
          name: Linter
          command: bundle exec rubocop

      - run:
          name: Database Setup
          command: bundle exec rake db:create db:schema:load

      - run:
          name: Tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml \
              --format progress \
              $TEST_FILES
      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
