default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  port: 5432
  username: postgres

test:
  <<: *default
  host: localhost
  database: hr_test

development:
  <<: *default
  host: localhost
  database: hr_development

production:
  <<: *default
  host: postgres
  database: hr_production
  password: <%= Rails.application.credentials.db_password %>
